name: Whatsapp
version: "2.0.1"
slug: whatsapp_addon
description: Whatsapp addon for Home Assistant using Baileys 7.0 (Latest WhatsApp Web API)
url: "https://github.com/pabloantonelli/ha-whatsapp"
# Original: https://github.com/giuseppecastaldo/ha-addons by Giuseppe Castaldo
homeassistant_api: true
hassio_api: true
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - config:rw
options:
  clients:
    - default
schema:
  clients:
    - str
