---
name: WhatsApp
version: "3.2.2"
slug: ha_whatsapp
description: Send and receive WhatsApp messages from Home Assistant, powered by Baileys
url: "https://github.com/pabloantonelli/ha-whatsapp"
homeassistant_api: true
hassio_api: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
ingress: true
ingress_port: 3000
panel_icon: mdi:whatsapp
panel_title: WhatsApp
map:
  - config:rw
  - media:rw
options:
  clients:
    - default
  log_level: info
schema:
  clients:
    - str
  api_token: password?
  log_level: list(trace|debug|info|warn|error|fatal)?
  mark_online: bool?
  refresh_hours: int(0,48)?
